### PR TITLE
Update spec text to support the new dateStyle/timeStyle.

### PR DESCRIPTION
**Pull request by fabalbon**

### CODE REVIEW

**Review by leobalter — APPROVED** [review]
Seems good to me, but it would be helpful to have another review here.

I have the same nitpicks for missing commas before _and_ in lists of 3 or more items. This is fine and we can get it fixed as a minor follow up

**Comment by zbraniecki** [comment]
Can I see it rendered somewhere?

**Comment by fabalbon** [comment]
> Can I see it rendered somewhere?

I'm using github pages to host the spec (index.html) from the main branch. I don't know if it's possible to make it also host that file from another branch.  Even if not ideal, an alternative would be to download the index.html file from this branch and open it locally.

**Review by FrankYFTang — APPROVED** [review]

**Comment by FrankYFTang** [comment]
@anba

**Pull request merged**
